# pod version 1.4.0

# Platform
platform :ios, '9.0'

# Swift Version
swift_version = '4.0'

# Use Frameworks
use_frameworks!

# Source
source 'https://github.com/CocoaPods/Specs.git'

# Workspace
workspace './PagingMenuControllerDemo.xcworkspace'

target 'PagingMenuControllerDemo' do
  pod "PagingMenuController", :path => "../"
end

target 'PagingMenuControllerDemo2' do
  pod "PagingMenuController", :path => "../"
end

target 'PagingMenuControllerDemoTests' do
  pod "PagingMenuController", :path => "../"
end
